/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package cms.core;



import cms.exception.InvalidInputException;
import cms.io.AppointmentFileRepository;
import cms.io.ReportFileRepository;
import cms.util.DateUtil;
import cms.util.ValidationUtil;
import java.util.List;

public class ReportService {

    private AppointmentFileRepository appointmentRepository;
    private ReportFileRepository reportRepository;

    public ReportService() {
        appointmentRepository = new AppointmentFileRepository();
        reportRepository = new ReportFileRepository();
    }

    public List<ReportSummary> getSavedReports() {
        return reportRepository.getAllReports();
    }

    public ReportSummary generateAndSaveReport(String reportType, String periodStart,
            String periodEnd, String generatedBy) throws InvalidInputException {
        validateReportRequest(reportType, periodStart, periodEnd, generatedBy);

        ReportSummary report = ReportSummary.generate(reportRepository.getNextReportId(),
                reportType, periodStart, periodEnd, generatedBy, DateUtil.now(),
                appointmentRepository.getAllAppointments());
        reportRepository.addReport(report);
        return report;
    }

    public String formatReport(ReportSummary report, String generatedByName) {
        StringBuilder text = new StringBuilder();
        text.append("Counseling Management System\n");
        text.append(report.getReportType()).append(" Appointment Report\n\n");
        text.append("Report ID: ").append(report.getReportId()).append("\n");
        text.append("Period: ").append(report.getPeriodStart()).append(" to ")
                .append(report.getPeriodEnd()).append("\n");
        text.append("Generated By: ").append(generatedByName).append("\n");
        text.append("Generated At: ").append(report.getGeneratedAt()).append("\n\n");
        text.append("Total Appointments: ").append(report.getTotalAppointments()).append("\n");
        text.append("Completed: ").append(report.getCompleted()).append("\n");
        text.append("Cancelled: ").append(report.getCancelled()).append("\n");
        text.append("Walk-in Bookings: ").append(report.getWalkIn()).append("\n");
        text.append("Online Bookings: ").append(report.getOnline()).append("\n");
        return text.toString();
    }

    private void validateReportRequest(String reportType, String periodStart,
            String periodEnd, String generatedBy) throws InvalidInputException {
        if (ValidationUtil.isEmpty(reportType) || ValidationUtil.isEmpty(periodStart)
                || ValidationUtil.isEmpty(periodEnd) || ValidationUtil.isEmpty(generatedBy)) {
            throw new InvalidInputException("Please fill in all report fields.");
        }

        if (!reportType.equals("Daily") && !reportType.equals("Monthly")
                && !reportType.equals("Quarterly") && !reportType.equals("Yearly")) {
            throw new InvalidInputException("Invalid report type.");
        }

        if (!ValidationUtil.isValidDate(periodStart) || !ValidationUtil.isValidDate(periodEnd)) {
            throw new InvalidInputException("Report dates must use yyyy-MM-dd format.");
        }
    }
}
